version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - feature/ci
  - master


# see http://status.appveyor.com/ re:connectivity issues for nuget
hosts:
 api.nuget.org: 93.184.221.200

init:
  # Good practise, because Windows
  - cmd: git config --global core.autocrlf true
install:
  # need to do the recursice clone here for submodules
  git submodule update --init --recursive
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # 
  - cmd: dotnet restore ./BreezeClient.sln
build_script:
  #
  - cmd: dotnet publish ./BreezeClient.sln
after_build:
  # For once the build has completed
on_finish :
  # any cleanup in here
deploy: off
